### ISSUE TITLE
Cannot use @types/leaflet

### ISSUE THREAD

**Issue by vlados** [shlomiassaf/webpack-dll-bundles-plugin#22]
I am trying to use https://github.com/Asymmetrik/ngx-leaflet 
I installed all the dependency packages but I encounter this error:
```
DLL: Checking if DLLs are valid.
{ Error: Cannot find module '@types/leaflet'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.resolve (internal/module.js:18:19)
    at DllBundlesControl.getPackageJsonPath (/Users/personal/code/udoma/webapp/node_modules/src/DllBundlesControl.ts:237:39)
    at DllBundlesControl.getPackageJson (/Users/personal/code/udoma/webapp/node_modules/src/DllBundlesControl.ts:224:32)
    at /Users/personal/code/udoma/webapp/node_modules/src/DllBundlesControl.ts:122:21
    at Array.map (<anonymous>)
    at DllBundlesControl.getMetadata (/Users/personal/code/udoma/webapp/node_modules/src/DllBundlesControl.ts:121:8)
    at DllBundlesControl.analyzeState (/Users/personal/code/udoma/webapp/node_modules/src/DllBundlesControl.ts:144:17)
    at DllBundlesControl.checkBundles (/Users/personal/code/udoma/webapp/node_modules/src/DllBundlesControl.ts:50:17)
    at DllBundlesPlugin.run (/Users/personal/code/udoma/webapp/node_modules/src/DllBundlesPlugin.ts:38:24)
    at Compiler.<anonymous> (/Users/personal/code/udoma/webapp/node_modules/src/DllBundlesPlugin.ts:31:53)
    at next (/Users/personal/code/udoma/webapp/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.<anonymous> (/Users/personal/code/udoma/webapp/node_modules/awesome-typescript-loader/src/watch-mode.ts:7:13)
    at Compiler.applyPluginsAsyncSeries (/Users/personal/code/udoma/webapp/node_modules/tapable/lib/Tapable.js:206:13)
    at applyPluginsAsync.err (/Users/personal/code/udoma/webapp/node_modules/webpack/lib/Compiler.js:277:9)
    at next (/Users/personal/code/udoma/webapp/node_modules/tapable/lib/Tapable.js:202:11) code: 'MODULE_NOT_FOUND' }
Error: Error: DllBundlesPlugin: Some packages have errors.
```

The package @types/leaflet is installed properly and everything is in the folder

**Comment by vlados** [comment]
For future reference the problem was that I installed the package with --save param
It should be in devDependancies
